### PR TITLE
Dolci/merge upstream

### PR DESCRIPTION
**Pull request by Ig-dolci**
Update Firedrake PETSc. The [Firedrake build](https://github.com/firedrakeproject/firedrake/pull/3689) was tested against this branch.

### CODE REVIEW

**Comment by JDBetteridge** [comment]
Have you also updated the SLEPc fork? https://github.com/firedrakeproject/firedrake/wiki/Updating-forked-dependencies

**Comment by Ig-dolci** [comment]
> Have you also updated the SLEPc fork? https://github.com/firedrakeproject/firedrake/wiki/Updating-forked-dependencies

Yes. The latest [Firedrake build](https://github.com/firedrakeproject/firedrake/pull/3689) tested this branch along with the SLEPc branch [dolci/merge_upstream](https://github.com/firedrakeproject/slepc/tree/dolci/merge_upstream). I also opened a [PR in the SLEPc repository](https://github.com/firedrakeproject/slepc/pull/7). 

Regarding the SLEPc and PETSc versions, the SLEPc version is [3.21.1](https://github.com/firedrakeproject/slepc/blob/dolci/merge_upstream/include/slepcversion.h#L15) and the PETSc version is [3.21.3](https://github.com/firedrakeproject/petsc/blob/dolci/merge_upstream/include/petscversion.h#L6).

**Review by JDBetteridge — APPROVED** [review]

**Comment by JDBetteridge** [comment]
Don't forget to announce the update on Slack before you merge!

**Comment by Ig-dolci** [comment]
> Don't forget to announce the update on Slack before you merge!

Right. Thanks! :) 🤞🏼

**Pull request merged**
