### PR TITLE
JDBetteridge/merge upstream

### PR DESCRIPTION
**Pull request by JDBetteridge**

### CODE REVIEW

**Comment by Ig-dolci** [comment]
We should update this PR with the latest PETSc changes that include the MPICH version update. This ensures PETSc installation on macOS Sequoia works. Can I do this?

**Comment by JDBetteridge** [comment]
I can update this and my SLEPc branch now, I'll retrigger Firedrake CI too, I want to test for compatibility with mpi4py==4.0

**Comment by Ig-dolci** [comment]
> I can update this and my SLEPc branch now, I'll retrigger Firedrake CI too, I want to test for compatibility with mpi4py==4.0

Perfect! Thanks.

**Comment by JDBetteridge** [comment]
Currently being tested here: https://github.com/firedrakeproject/firedrake/pull/3777

**Comment by JDBetteridge** [comment]
Having moved things forward again I'm running into issues:
https://github.com/firedrakeproject/firedrake/actions/runs/11181264621/job/31168588590?pr=3777
Seems like something may have changed with DMPlex:
```
ValueError: Mesh (firedrake_default_topology) already exists in /tmp/pytest-of-firedrake/pytest-0/popen-gw2/test_io_timestepping_setting_t0/test_io_timestepping_setting_time_dump.h5, but the global number of DMPlex points is inconsistent: 9
```

**Pull request merged**
